# Generated by Django 6.0.7 on 2026-07-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بهروز', max_length=100, verbose_name='نام')),
                ('title', models.CharField(default='توسعه دهنده', max_length=100, verbose_name='عنوان شغل اصلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('location', models.CharField(default='تهران،ایران', max_length=100, verbose_name='مکان')),
                ('profile_image', models.ImageField(upload_to='core/', verbose_name='تصویر پروفایل')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='core/', verbose_name='فایل رزومه')),
                ('home_bg_image', models.ImageField(upload_to='core/', verbose_name='تصویر پس زمینه اصلی')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon_class', models.CharField(help_text='feb fa-github : مثال', max_length=50, verbose_name='کلاس آیکون')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.generalsetting')),
            ],
        ),
    ]
