# Generated by Django 6.0.7 on 2026-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='enable_sound',
            field=models.BooleanField(default=True, verbose_name='نمایش کنترل صدا'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/', verbose_name='لوگو سایت'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='home_bg_image',
            field=models.ImageField(upload_to='core/', verbose_name='تصویر پس زمینه صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='location',
            field=models.CharField(default='تهران ، ایران', max_length=100, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(default='حمیدرضا رضا', max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='title',
            field=models.CharField(default='توسعه دهنده', max_length=100, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(help_text='مثال : fab fa-github', max_length=50, verbose_name='کلاس آیکون'),
        ),
    ]
