# Generated by Django 6.0.7 on 2026-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon_class', models.CharField(help_text='مثال : fas fa-desktop', max_length=50, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
