# Generated by Django 6.0.7 on 2026-07-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon_class', models.CharField(help_text='مثال : fas fa-desktop', max_length=50, verbose_name='کلاس آیکون')),
                ('subtitle', models.CharField(max_length=100, verbose_name='زیر عنوان')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon_class', models.CharField(help_text='مثال : fas fa-desktop', max_length=50, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon_class', models.CharField(help_text='مثال : fas fa-desktop', max_length=50, verbose_name='کلاس آیکون')),
                ('price', models.CharField(max_length=25, verbose_name='قیمت')),
                ('period', models.CharField(default='ماهانه', max_length=50, verbose_name='بازه زمانی')),
                ('features', models.TextField(verbose_name='ویژگی ها (هر خط یک مورد)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('image', models.ImageField(upload_to='testimonial/', verbose_name='عکس')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(verbose_name='نظر')),
            ],
        ),
    ]
