# Generated by Django 6.0.7 on 2026-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('experience', 'سوابق کاری'), ('education', 'سوابق تحصیلی')], max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال شروع')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال پایان')),
                ('company_or_field', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت / رشته')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام مهارت')),
                ('percentage', models.PositiveIntegerField(default=80, verbose_name='درصد تسلط')),
                ('display_type', models.CharField(choices=[('progress', 'Progress Bar'), ('chart', 'Chart')], default='progress', max_length=10, verbose_name='نوع مهارت')),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(verbose_name='مرحله')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'ordering': ['-step'],
            },
        ),
    ]
